export enum DataType {
	Texto = 'Texto',
	TextoGrande = 'TextoGrande',
	Numero = 'Numero',
	CPF = 'CPF',
	CNPJ = 'CNPJ',
	CPFouCNPJ = 'CPFouCNPJ',
	NumeroDeTelefone = 'NumeroDeTelefone',
	Data = 'Data',
	Hora = 'Hora',
	Email = 'Email',
	URL = 'URL',
	CEP = 'CEP',
	Moeda = 'Moeda',
	Senha = 'Senha',
	SimOuNao = 'SimOuNao',
	Cor = 'Cor',
}
