export enum DataType {
	Texto = 'Texto',
	TextoGrande = 'TextoGrande',
	Numero = 'Numero',
	CPF = 'CPF',
	CNPJ = 'CNPJ',
	Telefone = 'Telefone',
	Data = 'Data',
	Hora = 'Hora',
	Email = 'Email',
	URL = 'URL',
	CEP = 'CEP',
	Monetario = 'Monetario',
	Senha = 'Senha',
	CaixaDeOpcoes = 'CaixaDeOpcoes',
	Cor = 'Cor',
}
