import { InputDataType } from '../types';

export const DEFAULT_PLACEHOLDERS: Record<InputDataType, string> = {
	Texto: '',
	TextoGrande: '',
	Numero: '',
	CPF: 'Digite o CPF',
	CNPJ: 'Digite o CNPJ',
	Telefone: 'Digite Telefone',
	Data: '',
	Hora: '',
	Email: 'Digite o Email',
	URL: 'Digite a URL',
	CEP: 'Digite o CEP',
	Monetario: 'Digite o Valor',
	Senha: 'Digite a Senha',
	CaixaDeOpcoes: 'Selecione uma Opção',
	Cor: '',
};
